# Generated by Django 4.2.9 on 2024-01-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_users_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
