# Generated by Django 4.2.9 on 2024-01-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_users_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Designates whether Email is validated while user creation.'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text='Designates whether otp is validated while user creation.'),
        ),
    ]
